config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:new, :create, :index, :show] do
    resources :doses, only: [:new, :create, :destroy]
  end
  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader
  accepts_nested_attributes_for :doses, reject_if: proc { |c| c.attributes['ingredient_id'].blank?}
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: [:ingredient_id] }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = if params[:term]
      Cocktail.where('name LIKE ?', "%#{params[:term]}%")
    else
      Cocktail.all
    end
  end

  def show
    @cocktail = Cocktail.find(params[:id])
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
    @cocktail.doses.build
    @ingredients = Ingredient.all.order(:name)
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  private

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :term)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  def new
     @cocktail = Cocktail.find(params[:cocktail_id])
     @ingredients = Ingredient.all.order(:name)
     @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    @cocktail = @dose.cocktail
    if @dose.save
      redirect_to new_cocktail_dose_path(@dose.cocktail)
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = @cocktail.doses.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description,  :ingredient_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cocktails/index.html.erb
<div class="container">
  <h1>Find your perfect drink</h1>
  <div class="search-form">
    <%= form_tag(cocktails_path, method: :get) do %>
      <%= text_field_tag :term, params[:term] %>
      <%= submit_tag 'Search', name: nil %>
    <% end %>
  </div>
  <div class="row">
  <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-4">
      <!-- insert <div class="card"> -->
        <%= link_to cocktail_path(cocktail) do %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)),
           url('<%= cl_image_path cocktail.photo %>')">
            <div class="card-description">
              <h2><%= cocktail.name %></h2>
            </div>
          </div>
    </div>
        <% end %>
      <% end %>

  </div>
</div>

app/views/cocktails/new.html.erb
<div class="cocktail-wrapper">
    <div class="cocktail-image">
      <%= image_tag 'cocktails.jpg', height: 500, width: 500, crop: :fill %>
    </div>
  <div class="new-cocktail-container">
    <div class="form-cocktail">
        <%= simple_form_for(@cocktail) do |f| %><h1>Create a cocktail</h1>

          <%= f.input :name %>
          <%= f.input :photo %>
          <%= f.input :photo_cache, as: :hidden %>
          <%= f.submit class: 'btn-link' %>
        <% end %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="cocktail-wrapper">
  <div class="cocktail-image">
    <%= cl_image_tag @cocktail.photo, height: 500, width: 500, crop: :fill %>
  </div>
  <div class="cocktail-container">
    <div class="cocktail-container-content">
      <h1><%= @cocktail.name %></h1>

        <% @cocktail.doses.each do |dose| %>
         <p><%= dose.ingredient.name %>: <%= dose.description %>
          <%= link_to cocktail_dose_path(@cocktail, dose), method: :delete do %>
            <i class="fas fa-trash-alt"></i><% end %>
          </p>



        <% end %>

      <div class="buttons">
      <%= link_to "Back to cocktails", cocktails_path, class: "btn-link" %>  <%= link_to "Add an ingredient", new_cocktail_dose_path(@cocktail), class: "btn-link" %>
      </div>
    </div>
  </div>
</div>

app/views/doses/new.html.erb
<div class="new-dose-wrapper">
  <div class="new-cocktail-image" style="background-image: linear-gradient(rgba(0,0,0,0.2), rgba(0,0,0,0.1)),
           url('<%= cl_image_path @cocktail.photo,
      width: 500, height: 500, crop: :fill %>')">
    <h1><%= @cocktail.name %></h1>
    <div class="cocktail-ingredients">
      <% @cocktail.doses.each do |dose| %>
          <p><%= dose.ingredient.name %>: <%= dose.description %></p>
      <% end %>
    </div>
  </div>

  <div class="new-dose-container">
    <div class="form-cocktail">

        <h1>Add an ingredient</h1>
        <%= simple_form_for [@cocktail, @dose] do |f| %>
          <%= f.association :ingredient, collection: @ingredients, input_html: { class:'select2' } %>
          <%= f.input :description %>
        <div class="buttons">
          <%= f.submit "Add ingredient", class: 'btn-link', id: 'btn-add-ingredient' %>  <%= link_to "Cancel", cocktails_path, class: 'btn-link' %>
          <% end %>
        </div>
        <div class="finish">
          <%= link_to "Finish", cocktail_path(@cocktail), id: 'finish-cocktail', class: "finish-cocktail" %>
        </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag "application" %>

  </head>

  <body>
    <div class="navbar-wagon">
      <a href="/" class="navbar-wagon-brand">
        <%= image_tag "cocktail-logo.png", width: 50, height: 50%>
      </a>
  <!-- Right Navigation -->
      <div class="navbar-wagon-right hidden-xs hidden-sm">
        <%= link_to "Home", pages_home_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Cocktails", cocktails_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to "Add a cocktail", new_cocktail_path, class: "navbar-wagon-item navbar-wagon-link" %>
      </div>
    </div>
    <%= yield :above_container %>
    <div class="body-content" style="min-height: 80vh">
      <%= yield %>
    </div>

    <div class="footer">
    <div class="footer-copyright">
      This footer is made with <i class="fa fa-heart"></i> at Le Wagon
      </div>
    </div>
     <%= javascript_include_tag "application" %>
    <%= javascript_pack_tag "application" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-banner" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path("jtbkgoungjxuwvrl6y69",
      width: 400, height: 300, crop: :fill) %>')">
  <div class="banner-content">
    <h1>Miss Cocktail</h1>
    <%= link_to "Drinks for girls", cocktails_path, class: "btn-home" %>
  </div>
</div>